spring:
  application:
    name: CurdApplication
  datasource:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
    password: gopi0703
    url: jdbc:mysql://127.0.0.1:3306/Product
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
